#!/bin/bash

# Group number
GROUPNUMBER=8
# Node configs
CONFIGDIR=frrouting_cfg
# boot script name
BOOT="boot"
# startup script name
STARTUP="start"
PREFIXBASE="fde4:8"
PREFIXLEN=32
# You can reuse the above two to generate ip addresses/routes, ...

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"

    # P0 links to P1
    add_link P0 P1
    # P0 links to P2
    add_link P0 P2
    # P0 links to P3
    add_link P0 P3
    # P0 links to P4
    add_link P0 P4
    # P1 links to P2
    add_link P1 P2
    # P1 links to P3
    add_link P1 P3
    # P1 links to P4
    add_link P1 P4
    # P2 links to P5
    add_link P2 P5
    # P2 links to P6
    add_link P2 P6
    # P2 links to P9
    add_link P2 P9
    # P3 links to P7
    add_link P3 P7
    # P3 links to P8
    add_link P3 P8
    # P3 links to P9
    add_link P3 P9
    # P4 links to P5
    add_link P4 P5
    # P4 links to P6
    add_link P4 P6
    # P4 links to P7
    add_link P4 P7
    # P4 links to P8
    add_link P4 P8

    echo "@@Adding bridges nodes"

    bridge_node P0 eth3 hello

}

