#! /bin/sh
ldconfig
# Assigning IP addr for P2-eth0
ip link set dev P2-eth0 up
ip -6 addr add fde4:8:20::22/64

# Assigning IP addr for P2-eth1
ip link set dev P2-eth1 up
ip -6 addr add fde4:8:21::22/64

# Assigning IP addr for P2-eth2
ip link set dev P2-eth2 up
ip -6 addr add fde4:8:22::22/64

# Assigning IP addr for P2-lo
ip link set dev P2-lo up
ip -6 addr add fde4:8::22/128


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p2.api -i /tmp/p2_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p2_ospf.conf -z /tmp/p2.api -i /tmp/p2_ospf6d.pid -A 127.0.0.1
