#! /bin/sh
ldconfig
# Assigning IP addr for P3-eth0
ip link set dev P3-eth0 up
ip -6 addr add fde4:8:30::33/64

# Assigning IP addr for P3-eth1
ip link set dev P3-eth1 up
ip -6 addr add fde4:8:31::33/64

# Assigning IP addr for P3-eth2
ip link set dev P3-eth2 up
ip -6 addr add fde4:8:32::33/64

# Assigning IP addr for P3-lo
ip link set dev P3-lo up
ip -6 addr add fde4:8::33/128


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p3.api -i /tmp/p3_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p3_ospf.conf -z /tmp/p3.api -i /tmp/p3_ospf6d.pid -A 127.0.0.1
