#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8:00::00/128 dev lo

# Assigning IP addr for P0-eth0
ip link set dev P0-eth0 up
ip -6 addr add fde4:8:00:01::00/64 dev P0-eth0
# Assigning IP addr for P0-eth1
ip link set dev P0-eth1 up
ip -6 addr add fde4:8:00:02::00/64 dev P0-eth1
# Assigning IP addr for P0-eth2
ip link set dev P0-eth2 up
ip -6 addr add fde4:8:00:03::00/64 dev P0-eth2
# Assigning IP addr for P0-eth3
ip link set dev P0-eth3 up
ip -6 addr add fde4:8:00:04::00/64 dev P0-eth3
# Assigning IP addr for hello
ip link set dev hello up
ip -6 addr add fde4::8:cafe/48 dev hello

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p0.api -i /tmp/p0_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p0_ospf.conf -z /tmp/p0.api -i /tmp/p0_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p0_bgpd.conf -z /tmp/p0.api -i /tmp/p0_bgpd.pid -A 127.0.0.1 &
