#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8:00::55/128 dev lo

# Assigning IP addr for P5-eth0
ip link set dev P5-eth0 up
ip -6 addr add fde4:8:00:25::55/64 dev P5-eth0
# Assigning IP addr for P5-eth1
ip link set dev P5-eth1 up
ip -6 addr add fde4:8:00:45::55/64 dev P5-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p5.api -i /tmp/p5_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p5_ospf.conf -z /tmp/p5.api -i /tmp/p5_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p5_bgpd.conf -z /tmp/p5.api -i /tmp/p5_bgpd.pid -A 127.0.0.1 &
