#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8:00::77/128 dev lo

# Assigning IP addr for P7-eth0
ip link set dev P7-eth0 up
ip -6 addr add fde4:8:00:37::77/64 dev P7-eth0
# Assigning IP addr for P7-eth1
ip link set dev P7-eth1 up
ip -6 addr add fde4:8:00:47::77/64 dev P7-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p7.api -i /tmp/p7_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p7_ospf.conf -z /tmp/p7.api -i /tmp/p7_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p7_bgpd.conf -z /tmp/p7.api -i /tmp/p7_bgpd.pid -A 127.0.0.1 &
