#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8::11/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev P1-eth0 up
ip -6 addr add fde4:8:12::11/64 dev P1-eth0

# Assigning IP addr for P1-eth1
ip link set dev P1-eth1 up
ip -6 addr add fde4:8:13::11/64 dev P1-eth1

# Assigning IP addr for P1-eth2
ip link set dev P1-eth2 up
ip -6 addr add fde4:8:14::11/64 dev P1-eth2

# Assigning IP adrr for hello 
ip link set dev hello up
ip -6 addr add fde4::8:cafe/64 dev hello

#grp 9
ip link set dev grp9 up
ip -6 addr add fde4:8::beef/64 dev grp9

#grp 3
ip link set dev grp3 up
ip -6 addr add fde4:a8::bad/64 dev grp3

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p1.api -i /tmp/p1_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p1_ospf.conf -z /tmp/p1.api -i /tmp/p1_ospf6d.pid -A 127.0.0.1 &
# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p1_bgpd.conf -z /tmp/p1.api -i /tmp/p1_bgpd.pid -A 127.0.0.1 &
