#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8::2/128 dev lo

# Assigning IP addr for P2-eth0
ip link set dev P2-eth0 up
ip -6 addr add fde4:8:00:12::2/64 dev P2-eth0
# Assigning IP addr for P2-eth1
ip link set dev P2-eth1 up
ip -6 addr add fde4:8:00:23::2/64 dev P2-eth1
# Assigning IP addr for P2-eth2
ip link set dev P2-eth2 up
ip -6 addr add fde4:8:00:24::2/64 dev P2-eth2
# Assigning IP addr for P2-eth3
ip link set dev P2-eth3 up
ip -6 addr add fde4:8:00:25::2/64 dev P2-eth3
# Assigning IP addr for grp7
ip link set dev grp7 up
ip -6 addr add fde4:8:a007::cafe/48 dev grp7
# Assigning IP addr for grp4
ip link set dev grp4 up
ip -6 addr add fde4:8:b004::cafe/48 dev grp4

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p2.api -i /tmp/p2_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p2_ospf.conf -z /tmp/p2.api -i /tmp/p2_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p2_bgpd.conf -z /tmp/p2.api -i /tmp/p2_bgpd.pid -A 127.0.0.1 &
