#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8:00::44/128 dev lo

# Assigning IP addr for P4-eth0
ip link set dev P4-eth0 up
ip -6 addr add fde4:8:00:04::44/64 dev P4-eth0
# Assigning IP addr for P4-eth1
ip link set dev P4-eth1 up
ip -6 addr add fde4:8:00:14::44/64 dev P4-eth1
# Assigning IP addr for P4-eth2
ip link set dev P4-eth2 up
ip -6 addr add fde4:8:00:45::44/64 dev P4-eth2
# Assigning IP addr for P4-eth3
ip link set dev P4-eth3 up
ip -6 addr add fde4:8:00:46::44/64 dev P4-eth3
# Assigning IP addr for P4-eth4
ip link set dev P4-eth4 up
ip -6 addr add fde4:8:00:47::44/64 dev P4-eth4
# Assigning IP addr for P4-eth5
ip link set dev P4-eth5 up
ip -6 addr add fde4:8:00:48::44/64 dev P4-eth5

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p4.api -i /tmp/p4_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p4_ospf.conf -z /tmp/p4.api -i /tmp/p4_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p4_bgpd.conf -z /tmp/p4.api -i /tmp/p4_bgpd.pid -A 127.0.0.1 &
