#! /bin/sh
ldconfig

# Assigning IP addr fo lo
ip link set dev lo up
ip -6 addr add fde4:8::44/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev P4-eth0 up
ip -6 addr add fde4:8:14::44/64 dev P4-eth0

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p4.api -i /tmp/p4_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p4_ospf.conf -z /tmp/p4.api -i /tmp/p4_ospf6d.pid -A 127.0.0.1
