#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8::4/128 dev lo

# Assigning IP addr for P4-eth0
ip link set dev P4-eth0 up
ip -6 addr add fde4:8:00:14::4/64 dev P4-eth0
# Assigning IP addr for P4-eth1
ip link set dev P4-eth1 up
ip -6 addr add fde4:8:00:24::4/64 dev P4-eth1
# Assigning IP addr for P4-eth2
ip link set dev P4-eth2 up
ip -6 addr add fde4:8:00:48::4/64 dev P4-eth2
# Assigning IP addr for P4-eth3
ip link set dev P4-eth3 up
ip -6 addr add fde4:8:00:49::4/64 dev P4-eth3
# Assigning IP addr for P4-eth4
ip link set dev P4-eth4 up
ip -6 addr add fde4:8:00:4a::4/64 dev P4-eth4

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p4.api -i /tmp/p4_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p4_ospf.conf -z /tmp/p4.api -i /tmp/p4_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p4_bgpd.conf -z /tmp/p4.api -i /tmp/p4_bgpd.pid -A 127.0.0.1 &
