#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8::6/128 dev lo

# Assigning IP addr for P6-eth0
ip link set dev P6-eth0 up
ip -6 addr add fde4:8:00:0306::6/64 dev P6-eth0
# Assigning IP addr for P6-eth1
ip link set dev P6-eth1 up
ip -6 addr add fde4:8:00:0506::6/64 dev P6-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p6.api -i /tmp/p6_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p6_ospf.conf -z /tmp/p6.api -i /tmp/p6_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p6_bgpd.conf -z /tmp/p6.api -i /tmp/p6_bgpd.pid -A 127.0.0.1 &
