#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:8::9/128 dev lo

# Assigning IP addr for P9-eth0
ip link set dev P9-eth0 up
ip -6 addr add fde4:8:00:0409::9/64 dev P9-eth0
# Assigning IP addr for P9-eth1
ip link set dev P9-eth1 up
ip -6 addr add fde4:8:00:0509::9/64 dev P9-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p9.api -i /tmp/p9_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p9_ospf.conf -z /tmp/p9.api -i /tmp/p9_ospf6d.pid -A 127.0.0.1 &
#launching FFRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p9_bgpd.conf -z /tmp/p9.api -i /tmp/p9_bgpd.pid -A 127.0.0.1 &
